version: "3.8"
services:
  server:
    tty: true
    build: 
      context: .
      dockerfile: server/Dockerfile
    volumes:
      - .:/workspace:cached
    environment:
      API_KEY: ${API_KEY}
      API_KEY_SECRET: ${API_KEY_SECRET}
      BEARER_TOKEN: ${BEARER_TOKEN}
      ACCESS_TOKEN: ${CLIENT_SECRET}
      ACCESS_TOKEN_SECRET: ${CLIENT_SECRET}
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      REDIRECT_URI: ${REDIRECT_URI}
      EMAIL_SERVER: ${EMAIL_SERVER}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_FROM: ${EMAIL_FROM}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      EMAIL_TO: ${EMAIL_TO}
      EMAIL_SUBJECT: ${EMAIL_SUBJECT}
      EMAIL_BODY: ${EMAIL_BODY}
